spring.application.name=gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:9080/realms/bank-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:9080/realms/bank-realm/protocol/openid-connect/certs}

spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.bucket4j-rate-limiter.capacity=20
spring.cloud.gateway.routes[0].filters[0].args.bucket4j-rate-limiter.refillTokens=10
spring.cloud.gateway.routes[0].filters[0].args.bucket4j-rate-limiter.refillPeriod=1s
spring.cloud.gateway.routes[0].filters[0].args.bucket4j-rate-limiter.requestedTokens=1
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[1].id=transaction-service
spring.cloud.gateway.routes[1].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/transfers/**
spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.bucket4j-rate-limiter.capacity=10
spring.cloud.gateway.routes[1].filters[0].args.bucket4j-rate-limiter.refillTokens=10
spring.cloud.gateway.routes[1].filters[0].args.bucket4j-rate-limiter.refillPeriod=1s
spring.cloud.gateway.routes[1].filters[0].args.bucket4j-rate-limiter.requestedTokens=1
spring.cloud.gateway.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
