spring.application.name=discovery
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=discovery

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
